name: Manual deployment

on: workflow_dispatch

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version using git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --bumped-version --output version.txt
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Print
        run: |
          git branch
          tag=$(cat version.txt)
          echo $tag
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a "$tag" -m "new version tag"
          git push origin tag $tag
