name: Deploy on creation of tag
on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Add version file
      shell: bash
      run: echo "${{ github.ref_name }}" > build/resources/main/version.txt

    - name: Create jar
      run: |
        ./gradlew jar
        mv build/libs/wse-java.jar wse-app:wse-java:${{ github.ref_name }}.jar
        ls

    - name: Upload changelog
      uses: actions/upload-artifact@v4
      with:
        name: 'wse-app:wse-java:${{ github.ref_name }}'
        path: ./wse-app:wse-java:${{ github.ref_name }}.jar